
name: build-workflow

on:
  push:
    branches:
      - master
      - feature/*
      - fix/*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      PROJECT: ${{ secrets.DOCKER_PROJECT }}
      IMAGE_VERSION: dev
    steps:
      - name: checks out a copy of your repository
        uses: actions/checkout@v2
      - name: update ubuntu and install make tool
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make
      - name: download trivy and install trivy tool
        run: |
          TRIVY_VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/') ;
          curl -sfLo - https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz | sudo tar xz -C /usr/bin trivy || true          
      - name: docker registry authentication
        run: |
          docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.REGISTRY_URL}}
      - name: push docker image
        run: |
          make push        