
name: docker-ci-img

on:
  push:
    branches:
      - master
      - feature/*
      - fix/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checks out a copy of your repository
        uses: actions/checkout@v2
      - name: update ubuntu and install make tool
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make
      - name: github packages authentication
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        run: |
          make build        