
name: build-workflow

on:
  push:
    branches:
      - master
      - feature/*
      - fix/*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      PROJECT: $GITHUB_REPOSITORY
      IMAGE_VERSION: $GITHUB_REF
    steps:
      - name: checks out a copy of your repository
        uses: actions/checkout@v2
      - name: update ubuntu and install make tool
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make
      - name: github packages authentication
        run: |
          docker login $REGISTRY_URL -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}          
      - name: build docker image
        run: |
          make push        